apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-mysql
  labels:
    type: local
spec:
  #storageClassName: manual
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/helm/data"
